[package]
name = "basalgo"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
cargo-husky = { version = "1.5.0", features = ["run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
